### ISSUE TITLE
Static navigation banner giving 404

### ISSUE THREAD

**Issue by steveatlabor** [ny/universal-navigation#228]
The static navigation banner is giving a 404 looking for the resource xd_nygov.html . Because of relative pathing, the browser ends up trying to retrieve this resource from our HTTP servers, causing performance issues as thousands of users are trying to retrieve it, and each time it checks disk for the file.

To reproduce, go to:
https://static-assets.ny.gov/load_global_menu/ajax?iframe=true
in chrome and look at the console.

**Comment by judy-akers** [comment]
Do you know if there is a way to get the static nav to work with the alert banner? I am currently trying to fix the HESC.ny,gov website to handle this situation.

**Comment by mandyparker** [comment]
@judy-akers , did you try the instructions here:

https://github.com/ny/universal-navigation/blob/gh-pages/notes/static-option.md#inserting-functionality-for-emergency-and-news-alerts

**Comment by steveatlabor** [comment]
Ah, I guess that would fix my issue as well! Happy coincidence.

**Comment by judy-akers** [comment]
Yes, it runs into a problem with the X-Frame-Option on the Production server set to prevent cross site scripting.

Error message from Developer tools: "ajax?iframe=true&target=blank:1 Refused to display 'https://www.hesc.ny.gov/xd_nygov.html?en=0&gn=1&host=https%3A%2F%2Fstatic-assets.ny.gov%2Fload_global_menu%2Fajax%3Fiframe%3Dtrue%26target%3Dblank&height=111' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Judy A. Akers
Information Technology Specialist 3 (Programming, Public Website Infrastructure)

Office of Information Technology Services
50 Wolf Road
Albany New York 12232
Contacts - desk phone: (518) 486-6164 | cell: (518) 948-1433 | judy.akers@its.ny.gov<mailto:judy.akers@its.ny.gov>
www.ny.gov<http://www.ny.gov/> | support phone: (518) 457-3300 |  webnysupport@its.ny.gov<mailto:webnysupport@its.ny.gov>
*Please include ‘webnysupport@its.ny.gov’ on emails to me to ensure that in my absence, your issue is addressed by the WebNY team. Thank you! *
